include: "rules/common.smk"


##### Target rules #####


rule all:
    input:
        "results/filtered/all.snvs.selected.vcf.gz",
        "results/msa/snvs.fasta",
        "results/phylogeny/fasttree-snvs.nwk",


##### Modules #####


rule get_genome:
    """
    Download data from NCBI and place it to correct location
    """
    output:
        fasta="resources/genome.fasta",
        zip=temp("resources/datasets/ref.zip"),
        dir=temp(directory("resources/datasets/ref")),
    log:
        "logs/datasets/ref.log",
    # wildcard_constraints:
    #     sample=ACCESSION_SAMPLES
    conda:
        "envs/ncbi-datasets.yaml"
    params:
        accession=ref_id,
    shell:
        """
        datasets download genome accession {params.accession} --include genome --filename {output.zip}
        unzip {output.dir}.zip -d {output.dir}
        mv {output.dir}/ncbi_dataset/data/{params.accession}/{params.accession}*_genomic.fna {output.fasta}
        """


rule get_fastq_pe_gz:
    output:
        # the wildcard name must be accession, pointing to an SRA number
        "resources/reads/{accession}_1.fastq.gz",
        "resources/reads/{accession}_2.fastq.gz",
    log:
        "logs/fasterq-dump/{accession}.gz.log",
    threads: 6  # defaults to 6
    params:
        extra="--skip-technical",
    wrapper:
        "v9.8.0/bio/sra-tools/fasterq-dump"


# include: "rules/ref.smk"
# skipped variants (vep)


checkpoint genome_faidx:
    input:
        "resources/genome.fasta",
    output:
        "resources/genome.fasta.fai",
    log:
        "logs/genome-faidx.log",
    cache: True
    params:
        extra="",
    wrapper:
        "v8.1.1/bio/samtools/faidx"


rule intervals_from_fai:
    input:
        "resources/genome.fasta.fai",
    output:
        "resources/intervals.list",
    log:
        "logs/intervals-from-fai.log",
    shell:
        "cut -f1 {input} > {output} 2> {log}"


rule genome_dict:
    input:
        "resources/genome.fasta",
    output:
        "resources/genome.dict",
    log:
        "logs/samtools/create_dict.log",
    cache: True
    conda:
        "envs/samtools.yaml"
    shell:
        "samtools dict {input} > {output} 2> {log} "


rule bwa_index:
    input:
        "resources/genome.fasta",
    output:
        idx=multiext("resources/genome.fasta", ".amb", ".ann", ".bwt", ".pac", ".sa"),
    log:
        "logs/bwa_index.log",
    wrapper:
        "v5.10.0/bio/bwa/index"


include: "rules/mapping.smk"


# include: "rules/calling.smk"

if "restrict-regions" in config["processing"]:

    rule compose_regions:
        input:
            config["processing"]["restrict-regions"],
        output:
            "results/called/{contig}.regions.bed",
        conda:
            "envs/bedops.yaml"
        shell:
            "bedextract {wildcards.contig} {input} > {output}"


rule call_variants:
    input:
        bam=get_sample_bams_dedup,
        bai=get_sample_bai_dedup,
        ref="resources/genome.fasta",
        fai="resources/genome.fasta.fai",
        idx="resources/genome.dict",
    output:
        gvcf="results/called/{sample}.g.vcf.gz",
    log:
        "logs/gatk/haplotypecaller/{sample}.log",
    threads: 4
    resources:
        mem_mb=1024,
    params:  # Some need to be moved to config
        extra="-G StandardAnnotation -G AS_StandardAnnotation -G StandardHCAnnotation "
        + config["params"]["gatk"]["HaplotypeCaller"]
        + " -sample-name {sample}",
    wrapper:
        "v7.6.0/bio/gatk/haplotypecaller"


rule genomics_db_import:
    input:
        gvcfs=expand("results/called/{sample}.g.vcf.gz", sample=samples.index),
        interval_list="resources/intervals.list",
    output:
        db=directory("results/genomicsdb"),
    log:
        "logs/gatk/genomicsdbimport.log",
    threads: 2
    resources:
        mem_mb=lambda wildcards, input: max([input.size_mb * 1.6, 200]),
    params:
        intervals=lambda w, input: input.interval_list,
        db_action="create",  # optional
        extra="",  # optional
        java_opts="",  # optional
    wrapper:
        "v7.6.0/bio/gatk/genomicsdbimport"


#####################################
# Genotype the GVCFs
#####################################


rule genotype_gvcfs:
    input:
        genomicsdb="results/genomicsdb",
        # gvcf="calls/all.g.vcf",  # combined gvcf over multiple samples
        # N.B. gvcf or genomicsdb must be specified
        # in the latter case, this is a GenomicsDB data store
        ref="resources/genome.fasta",
    output:
        vcf="results/genotyped/all.vcf.gz",
    log:
        "logs/gatk/genotypegvcfs.log",
    resources:
        mem_mb=1024,
    params:
        extra="",  # optional
        java_opts="",  # optional
    wrapper:
        "v7.6.0/bio/gatk/genotypegvcfs"


# include: "rules/filtering.smk"


rule select_calls:
    input:
        ref="resources/genome.fasta",
        vcf="results/genotyped/all.vcf.gz",
    output:
        vcf=temp("results/filtered/all.{vartype}.raw.vcf.gz"),
    log:
        "logs/gatk/selectvariants/{vartype}.log",
    params:
        extra=get_vartype_arg,
    wrapper:
        "v7.6.0/bio/gatk/selectvariants"


rule filter_calls:
    input:
        ref="resources/genome.fasta",
        vcf="results/filtered/all.{vartype}.raw.vcf.gz",
    output:
        vcf=temp("results/filtered/all.{vartype}.hardfiltered.vcf.gz"),
    params:
        filters=get_filter,
        extra="",  # optional arguments; could add --genotype-filter-expression 'GQ < 50.0' --genotype-filter-name "genotype_filters" --set-filtered-genotype-to-no-call
    log:
        "logs/gatk/variantfiltration/{vartype}.log",
    wrapper:
        "v7.6.0/bio/gatk/variantfiltration"


rule select_pass_calls:
    input:
        vcf="results/filtered/all.{vartype}.hardfiltered.vcf.gz",
        ref="resources/genome.fasta",
    output:
        vcf="results/filtered/all.{vartype}.selected.vcf.gz",
    log:
        "logs/gatk/select-pass/{vartype}.log",
    resources:
        mem_mb=1024,
    params:
        extra="--exclude-filtered",  # optional filter arguments, see GATK docs
        java_opts="",  # optional
    wrapper:
        "v7.6.0/bio/gatk/selectvariants"


# Based on best practices we could add Filter Variants by Variant (Quality Score) Recalibration
#  Tools involved: VariantRecalibrator, ApplyVQSB
#  //Need to adjust this part//
# rule recalibrate_calls:
#     input:
#         vcf="results/filtered/all.{vartype}.selected.vcf.gz"
#     output:
#         vcf=temp("results/filtered/all.{vartype}.recal.vcf.gz"),
#     params:
#         extra=config["params"]["gatk"]["VariantRecalibrator"],
#     log:
#         "logs/gatk/variantrecalibrator/{vartype}.log",
#     wrapper:
#         "v7.6.0/bio/gatk/variantrecalibrator"
#
#
# rule apply_vqsr:
#     input:
#         vcf="results/filtered/all.{vartype}.recal.vcf.gz",
#         recal="snps.recal",
#         tranches="snps.tranches",
#         ref="resources/genome.fasta",
#     output:
#         vcf="results/filtered/all.{vartype}.recalibrated.vcf.gz",
#     log:
#         "logs/gatk/applyvqsr.log",
#     params:
#         mode="SNP",  # set mode, must be either SNP, INDEL or BOTH
#         extra="",  # optional
#     resources:
#         mem_mb=1024,
#     wrapper:
#         "v7.6.0/bio/gatk/applyvqsr"


# include: "rules/stats.smk"
include: "rules/qc.smk"


# include: "rules/annotation.smk"


# filter before extracting FASTA
rule bcf_filter_o_vcf_gz:
    input:
        "results/filtered/all.snvs.selected.vcf.gz",
    output:
        temp("results/msa/all.snvs.filtered.vcf.gz"),
    log:
        "logs/bcftools/filter-msa.log",
    params:
        filter="--SnpGap 3 -e 'QUAL < 1000 || AF=1 || INFO/AF < 0.05 || F_MISSING > 0'",
        extra="",
    wrapper:
        "v8.1.1/bio/bcftools/filter"


rule msa_ref_fasta:
    input:
        "results/msa/all.snvs.filtered.vcf.gz",
    output:
        temp("results/msa/ref.fasta"),
    log:
        "logs/bcftools/filter-msa-ref.log",
    conda:
        "envs/variant.yaml"
    shell:
        """
        printf ">REF\n%s\n" \
        $(bcftools query -f '%REF' {input} | tr -d '\n') > {output} 2> {log}
        """


rule msa_sample_fasta:
    input:
        "results/msa/all.snvs.filtered.vcf.gz",
    output:
        temp("results/msa/{sample}.fasta"),
    conda:
        "envs/variant.yaml"
    log:
        "logs/bcftools/filter-msa-{sample}.log",
    shell:
        """
        printf ">{wildcards.sample}\n%s\n" \
        $(bcftools query -s {wildcards.sample} -f '[%IUPACGT]' {input} | tr -d '\n') > {output} 2> {log}
        """


rule concat_fasta:
    input:
        ref="results/msa/ref.fasta",
        samples=expand("results/msa/{sample}.fasta", sample=samples.index),
    output:
        "results/msa/snvs.fasta",
    log:
        "logs/concat_fasta.log",
    shell:
        """
        cat {input.ref} {input.samples} > {output}
        """


# Phylogeny


rule fasttree:
    input:
        alignment="results/msa/{alnname}.fasta",  # Input alignment file
    output:
        tree="results/phylogeny/fasttree-{alnname}.nwk",  # Output tree file
    log:
        "logs/fasttree/fasttree-{alnname}.log",
    params:
        extra="-gtr -gamma -nt",  # Additional arguments
    wrapper:
        "v7.3.0/bio/fasttree"
