include: "rules/common.smk"


##### Target rules #####


rule all:
    input:
        "results/filtered/all.snvs.selected.vcf.gz",
        "results/msa/snvs.fasta",
        "results/phylogeny/fasttree-snvs.nwk",
        "results/qc/multiqc.html",


##### Modules #####

rule prepare_reference:
    """
    Prepare reference genome and annotation
    from local files or NCBI.
    """
    output:
        fasta="resources/genome.fasta",
        gff="resources/genes.gff3"
    params:
        source=config["reference"]["source"],
        accession=config["reference"].get("accession", ""),
        local_fasta=config["reference"].get("fasta", ""),
        local_gff=config["reference"].get("gff", "")
    conda:
        "envs/ncbi-datasets.yaml"
    log:
        "logs/reference.log"
    shell:
        """
        mkdir -p resources
        mkdir -p tmp/reference

        # Always clean up temp folder afterwards
        trap 'rm -rf tmp/reference' EXIT

        if [ "{params.source}" = "local" ]; then

            ln -sf $(realpath {params.local_fasta}) {output.fasta}
            ln -sf $(realpath {params.local_gff}) {output.gff}

        elif [ "{params.source}" = "ncbi" ]; then

            datasets download genome accession {params.accession} \
                --include genome,gff3 \
                --filename tmp/reference/reference.zip \
                > {log} 2>&1

            unzip -o tmp/reference/reference.zip \
                -d tmp/reference >> {log} 2>&1

            GENOME=$(find tmp/reference -name "*genomic.fna" | head -n1)
            GFF=$(find tmp/reference -name "*.gff*" | head -n1)

            if [ -z "$GENOME" ] || [ -z "$GFF" ]; then
                echo "Genome or GFF not found in downloaded dataset" >&2
                exit 1
            fi

            cp "$GENOME" {output.fasta}
            cp "$GFF" {output.gff}

        else
            echo "Invalid reference source: {params.source}" >&2
            exit 1
        fi
        """

# And look in to this: https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/bio/sra-tools/fasterq-dump.html 
# Update the rest and make more in wrappers.

# Make a distinction between local genomes and remote genomes that need to be fetched and/ or both should also be supported.
# Two tables one with local genome logic and another with remote genome logic? Or one table with a column that specifies local vs remote and then logic in the rule to handle both cases?

rule genome_faidx:
    input:
        "resources/genome.fasta",
    output:
        "resources/genome.fasta.fai",
    log:
        "logs/genome-faidx.log",
    cache: True
    params:
        extra="",
    wrapper:
        "v8.1.1/bio/samtools/faidx"


rule intervals_from_fai:
    input:
        "resources/genome.fasta.fai",
    output:
        "resources/intervals.list",
    shell:
        "cut -f1 {input} > {output}"


rule genome_dict:
    input:
        "resources/genome.fasta",
    output:
        "resources/genome.dict",
    log:
        "logs/samtools/create_dict.log",
    conda:
        "envs/samtools.yaml"
    cache: True
    shell:
        "samtools dict {input} > {output} 2> {log} "


rule bwa_index:
    input:
        "resources/genome.fasta",
    output:
        idx=multiext("resources/genome.fasta", ".amb", ".ann", ".bwt", ".pac", ".sa"),
    log:
        "logs/bwa_index.log",
    wrapper:
        "v5.10.0/bio/bwa/index"


include: "rules/mapping.smk"

if "restrict-regions" in config["processing"]:

    rule compose_regions:
        input:
            config["processing"]["restrict-regions"],
        output:
            "results/called/{contig}.regions.bed",
        conda:
            "envs/bedops.yaml"
        shell:
            "bedextract {wildcards.contig} {input} > {output}"


rule call_variants:
    input:
        bam=get_sample_bams_dedup,
        bai=get_sample_bai_dedup,
        ref="resources/genome.fasta",
        idx="resources/genome.dict",
        # known="resources/variation.noiupac.vcf.gz",
        # tbi="resources/variation.noiupac.vcf.gz.tbi",
    output:
        gvcf=protected("results/called/{sample}.g.vcf.gz"),
    log:
        "logs/gatk/haplotypecaller/{sample}.log",
    params: # Some need to be moved to config
        extra="-G StandardAnnotation -G AS_StandardAnnotation -G StandardHCAnnotation " +
              config["params"]["gatk"]["HaplotypeCaller"] +
              " -sample-name {sample}"       
    threads: 4
    resources:
        mem_mb=1024,
    wrapper:
        "v7.6.0/bio/gatk/haplotypecaller"


rule genomics_db_import:
    input:
        gvcfs=expand(
            "results/called/{sample}.g.vcf.gz", sample=samples.index
        ),
        interval_list="resources/intervals.list",
    output:
        db=directory("results/genomicsdb"),
    log:
        "logs/gatk/genomicsdbimport.log",
    params:
        intervals=lambda w, input: input.interval_list,
        db_action="create",  # optional
        extra="",  # optional
        java_opts="",  # optional
    threads: 2
    resources:
        mem_mb=lambda wildcards, input: max([input.size_mb * 1.6, 200]),
    wrapper:
        "v7.6.0/bio/gatk/genomicsdbimport"


#####################################
# Genotype the GVCFs
#####################################

rule genotype_gvcfs:
    input:
        genomicsdb="results/genomicsdb",
        # gvcf="calls/all.g.vcf",  # combined gvcf over multiple samples
        # N.B. gvcf or genomicsdb must be specified
        # in the latter case, this is a GenomicsDB data store
        ref="resources/genome.fasta",
    output:
        vcf="results/genotyped/all.vcf.gz",
    log:
        "logs/gatk/genotypegvcfs.log"
    params:
        extra="",  # optional
        java_opts="", # optional
    resources:
        mem_mb=1024
    wrapper:
        "v7.6.0/bio/gatk/genotypegvcfs"


rule select_calls:
    input:
        ref="resources/genome.fasta",
        vcf="results/genotyped/all.vcf.gz",
    output:
        vcf=temp("results/filtered/all.{vartype}.raw.vcf.gz"),
    params:
        extra=get_vartype_arg,
        # --restrict-alleles-to BIALLELIC --create-output-variant-index false
    log:
        "logs/gatk/selectvariants/{vartype}.log",
    wrapper:
        "v7.6.0/bio/gatk/selectvariants"


rule filter_calls:
    input:
        ref="resources/genome.fasta",
        vcf="results/filtered/all.{vartype}.raw.vcf.gz",
    output:
        vcf=temp("results/filtered/all.{vartype}.hardfiltered.vcf.gz"),
    params:
        filters=get_filter,
        extra="",  # optional arguments; could add --genotype-filter-expression 'GQ < 50.0' --genotype-filter-name "genotype_filters" --set-filtered-genotype-to-no-call
    log:
        "logs/gatk/variantfiltration/{vartype}.log",
    wrapper:
        "v7.6.0/bio/gatk/variantfiltration"


rule select_pass_calls:
    input:
        vcf="results/filtered/all.{vartype}.hardfiltered.vcf.gz",
        ref="resources/genome.fasta",
    output:
        vcf="results/filtered/all.{vartype}.selected.vcf.gz",
    log:
        "logs/gatk/select-pass/{vartype}.log",
    params:
        extra="--exclude-filtered",  # optional filter arguments, see GATK docs
        java_opts="",  # optional
    resources:
        mem_mb=1024,
    wrapper:
        "v7.6.0/bio/gatk/selectvariants"

include: "rules/qc.smk"

# filter before extracting FASTA
rule bcf_filter_o_vcf_gz:
    input:
        "results/filtered/all.snvs.selected.vcf.gz",
    output:
        temp("results/msa/all.snvs.filtered.vcf.gz"),
    log:
        "logs/bcftools/filter-msa.log",
    params:
        filter="--SnpGap 3 -e 'QUAL < 1000 || AF=1 || INFO/AF < 0.05 || F_MISSING > 0'",
        extra="",
    wrapper:
        "v8.1.1/bio/bcftools/filter"


rule msa_ref_fasta:
    input:
        "results/msa/all.snvs.filtered.vcf.gz",
    output:
        temp("results/msa/ref.fasta"),
    conda:
        "envs/variant.yaml",
    log:
        "logs/bcftools/filter-msa-ref.log",
    shell:
        """
        printf ">REF\n%s\n" \
        $(bcftools query -f '%REF' {input} | tr -d '\n') > {output} 2> {log}
        """


rule msa_sample_fasta:
    input:
        "results/msa/all.snvs.filtered.vcf.gz",
    output:
        temp("results/msa/{sample}.fasta"),
    conda:
        "envs/variant.yaml",
    log:
        "logs/bcftools/filter-msa-{sample}.log",
    shell:
        """
        printf ">{wildcards.sample}\n%s\n" \
        $(bcftools query -s {wildcards.sample} -f '[%IUPACGT]' {input} | tr -d '\n') > {output} 2> {log}
        """


rule concat_fasta:
    input:
        ref="results/msa/ref.fasta",
        samples=expand("results/msa/{sample}.fasta", sample=samples.index)
    output:
        "results/msa/snvs.fasta"
    shell:
        """
        cat {input.ref} {input.samples} > {output}
        """


# Phylogeny
rule fasttree:
    input:
        alignment="results/msa/{alnname}.fasta",  # Input alignment file
    output:
        tree="results/phylogeny/fasttree-{alnname}.nwk",  # Output tree file
    log:
        "logs/fasttree/fasttree-{alnname}.log",
    params:
        extra="-gtr -gamma -nt",  # Additional arguments
    wrapper:
        "v7.3.0/bio/fasttree"
